# Privoxy configuration template for torproxy
confdir /etc/privoxy
logdir /var/log/privoxy
actionsfile match-all.action
actionsfile default.action
actionsfile user.action
filterfile default.filter
filterfile user.filter

logfile logfile
#log-messages 1
#log-highlight-messages 1

listen-address 0.0.0.0:8118
toggle 1
enable-remote-toggle 0
enable-remote-http-toggle 0
enable-edit-actions 0
enforce-blocks 0
buffer-limit 4096
enable-proxy-authentication-forwarding 0
forwarded-connect-retries 0
accept-intercepted-requests 1
allow-cgi-request-crunching 0
split-large-forms 0
keep-alive-timeout 5
tolerate-pipelining 1
default-server-timeout 60
connection-sharing 0

# Bypass Tor for localhost and local subnets
forward localhost/ .
forward 127.*.*.*/ .
forward 10.*.*.*/ .
forward 172.16.*.*/ .
forward 172.17.*.*/ .
forward 172.18.*.*/ .
forward 172.19.*.*/ .
forward 172.20.*.*/ .
forward 172.21.*.*/ .
forward 172.22.*.*/ .
forward 172.23.*.*/ .
forward 172.24.*.*/ .
forward 172.25.*.*/ .
forward 172.26.*.*/ .
forward 172.27.*.*/ .
forward 172.28.*.*/ .
forward 172.29.*.*/ .
forward 172.30.*.*/ .
forward 172.31.*.*/ .
forward 192.168.*.*/ .

# Forward all other traffic through Tor SOCKS5t proxy
forward-socks5t / 127.0.0.1:9050 .
